LRQA-66638
emanuelfisilva/liferay-portal pull request #154
Opened 2021-04-28 06:34 UTC by guivilarim

2021-04-28 06:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-04-28 06:38 UTC, guivilarim commented
ci:test

2021-04-28 06:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8222/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8222/jenkins-report.html">here</a>.</b></p>

2021-04-28 18:22 UTC, guivilarim commented
ci:test:sf

2021-04-28 18:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5720/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5720/jenkins-report.html">here</a>.</b></p>

2021-04-28 18:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9b0daad537e873f253fb5a91ce15258c8e830be5">9b0daad537e873f253fb5a91ce15258c8e830be5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-66638">LRQA-66638</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/e3351886ce7833b3015c5cca8a43816cc22cc18e">e3351886ce7833b3015c5cca8a43816cc22cc18e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5720/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5720/jenkins-report.html">here</a>.</h5><pre><code>format-source-files:
[stopwatch] [run.batch.test.action: 1:44.916 sec]
     [echo] 
      [get] Getting: http://test-1-21/job/test-portal-source-format/5720//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210428114659748.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210428114659748.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null350185489.properties</code></pre></details></html>

2021-04-28 18:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5720/">test-portal-source-format#5720</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5720/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/emanuelfisilva/liferay-portal/pull/154">emanuelfisilva#154</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529237617">[master] ci:test:sf - guivilarim &gt; emanuelfisilva - PR#154 - 2021-04-28[11:23:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/516/">publish-testray-report#516</a><br/></div></div>

2021-04-29 13:07 UTC, emanuelfisilva commented on portal-web/test/functional/com/liferay/portalweb/macros/DataEngine.macro
> +		);
You could let this end of parenthesis and semi-colon on the upper line

2021-04-29 13:08 UTC, emanuelfisilva commented on portal-web/test/functional/com/liferay/portalweb/macros/DataEngine.macro
> +		MenuItem.click(menuItem = "Edit");
Please, remember to insert a line break between actions to increase readability.

2021-04-29 13:28 UTC, emanuelfisilva requested changes
Your code is not compiling:
```
Unexpected closing boundary at:
     [exec]     /home/emanuel/lportal/portal-master/liferay-portal/modules/apps/data-engine/data-engine-test/src/testFunctional/tests/wem/translations/LocalizedFieldsetsWebContent.testcase:492
     [exec]         webContentTitle = "Web Content Title");
```
Your last commit _e3351886ce7833b3015c5cca8a43816cc22cc18e_ deletes the test **DefaultTitleIsDisplayedUponLocaleChange**.

Also, please run SF on your branch.

Thanks.

2021-04-30 18:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/2942/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-source-format/builds/2942/jenkins-report.html">here</a>.</b></p>

2021-04-30 18:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/648105cf63932af9173a603bb43e553b7d7793df">648105cf63932af9173a603bb43e553b7d7793df</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-66638">LRQA-66638</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/7eadc9f1c5dc82ac3a6f02ed52f49da231340b7e">7eadc9f1c5dc82ac3a6f02ed52f49da231340b7e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2942/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2942/jenkins-report.html">here</a>.</h5></details></html>

2021-04-30 18:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2942/">test-portal-source-format#2942</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2942/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/emanuelfisilva/liferay-portal/pull/154">emanuelfisilva#154</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529812256">[master] ci:test:sf - guivilarim &gt; emanuelfisilva - PR#154 - 2021-04-30[11:13:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/504/">publish-testray-report#504</a><br/></div></div>

2021-05-04 01:21 UTC, guivilarim commented
ci:test:sf

2021-05-04 01:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4679/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4679/jenkins-report.html">here</a>.</b></p>

2021-05-04 01:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a31589a97b13d747dcc409156d4e67907ead0bfd">a31589a97b13d747dcc409156d4e67907ead0bfd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-66638">LRQA-66638</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/255b268e2ef9d76f3c31f56b912f3f7c59f0ec9c">255b268e2ef9d76f3c31f56b912f3f7c59f0ec9c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4679/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4679/jenkins-report.html">here</a>.</h5></details></html>

2021-05-04 01:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4679/">test-portal-source-format#4679</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4679/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/emanuelfisilva/liferay-portal/pull/154">emanuelfisilva#154</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530070490">[master] ci:test:sf - guivilarim &gt; emanuelfisilva - PR#154 - 2021-05-03[18:21:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/618/">publish-testray-report#618</a><br/></div></div>

2021-05-13 11:42 UTC, emanuelfisilva commented
Closing this as the development of this task is blocked.
Please, rebase and resend when we can continue with this.

2021-05-13 11:42 UTC, closed without merging